isomerpages/moe-marisstellahigh

_for-parents/For Parents (Primary)/For Parents (Primary).md
=> Useful Link for Parent - Family matters (removed)

_academic-programme/Primary/Academic Programme.md
Link to the correct page for PE and ICT(Pri). Kindly help to approve.
=> Academic Program (primary)

_our-staff/Primary/Department.md
=> Update: Our Staff (Primary)

_admission/FAQs (Secondary).md, _announcements/Announcements (Secondary).md
updated open house faqs for 2023
=> Updates on Open House FAQs

_our-staff/Primary/Class.md, _our-staff/Primary/Department.md
Update Class Form teacher page. update department page
=> Update on Our Staff

_announcements/Announcements (Primary).md
update on closing dates for canteen advertisement.
=> Update on Announcement

_our-partners/Parents Support Group/Contact Us.md
=> PSG page update

_our-partners/Parents Support Group/Contact Us.md
=> PSG link update

_for-parents/For Parents (Primary)/Books, Uniform and Name Tag.md
updated the number for school bookshop
=> Update of School Bookshop Tel

_announcements/Announcements (Primary).md, _for-parents/For Parents (Primary)/For Parents.md
changed the deadline for canteen vendors adv
removed link for yearbook 2022
=> Updates on school website

_our-staff/Primary/Class.md, _our-staff/Primary/Department.md
Remove colleagues whom have left. Added in new colleagues
=> Update on Staff

_for-parents/For Parents (Primary)/For Parents.md, _our-staff/Primary/Class.md, _our-staff/Primary/Department.md
remove 2022 magazine flipped link
added 2023 magazine google drive link
made some changes to teachers' name
=> Website update

_announcements/Announcements (Primary).md
change the day of advertisment
=> canteen vendor advertisment

_config.yml, pages/testing page.md
=> reponsive web design

_data/navigation.yml, pages/testing page.md
=> remove test

_our-staff/Primary/Class.md, _our-staff/Primary/Department.md
=> Amending name

_our-staff/Primary/Department.md
=> removal of staff name

_announcements/Announcements (Secondary).md
=> open house

_announcements/Announcements (Primary).md
remove the advertisement for drinks stall
=> Removal of advertisement

_admission/Admission (Secondary)/2025 Sec 1 Registration.md
=> S1 Orientation Timing Change

_admission/Admission (Primary)/Waitlist Application.md
added in info for admission page
=> Updated Admission Page

_announcements/Announcements (Primary).md
Advertisement under Announcement for canteen vendor
=> Advertisement

_announcements/Announcements (Primary).md
=> canteen ads
